# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 
    url: ''
    weight: 20
  - name: Home
    url: '#000_about'
    weight: 70
  - name: Projects
    url: '#100_projects'
    weight: 80
  - name: Publications
    url: '#200_featured'
    weight: 90
  # - name: Posts
  #   url: '#posts'
  #   weight: 30
  # - name: Talks
  #   url: '#talks'
  #   weight: 40
  # - name: Publications
  #   url: '#featured'
  #   weight: 50
  - name: Contact
    url: '#contact'
    weight: 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
